### ISSUE TITLE
Etapa pré-avaliação para ad hoc

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#103]
@wilsonmoura é possível criar uma etapa para que o parecerista ad hoc confirme a disponibilidade para avaliação. Só após ele ter confirmado que está disponível é que ele poderia acessar a documentação da revista a ser avaliada.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula a sugestão seria incluir mais um botão de ação (veja imagem) para que o parecerista decida se quer recusar a avaliação do periódico.
![screenshot-avaliacao lilacs homolog bvsalud org-2020 05 04-14-57-11](https://user-images.githubusercontent.com/3779520/80997492-c80e6500-8e17-11ea-9b01-f0c4f058b7db.png)

**Comment by AngelicaSAPaula** [comment]
Ok, de acordo! Podemos fazer desta maneira!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula testar no ambiente de homologação.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula recurso disponível para testes no ambiente de homologação.

**Comment by AngelicaSAPaula** [comment]
Ok, já é possível ver o ícone de recusa. É possível alterar de lixeira para um "X"?

![image](https://user-images.githubusercontent.com/47643830/82942185-f6421900-9f6d-11ea-8cbd-d754a7ac0690.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ícone alterado conforme solicitação.

**Comment by AngelicaSAPaula** [comment]
Ok, ícone aparece adequadamente!
