### ISSUE TITLE
Label perfis

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#106]
Favor alterar o nome do perfil da "Secretaria" para "Coordenação". Desta forma, no perfil dos usuários, a abreviação ficaria como "C".

Além disso, alterar:
• Parecerista Ad Hoc - "P"

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula os nomes têm que estar em inglês:

- Coordenação >> Coordination >> C - **OK**
- Parecerista Ad hoc >> Ad hoc Member ou Member Ad hoc >> A ou M - Iniciais iguais, respectivamente, a dos perfis Administrador e Membro do Comitê

Minha sugestão é mudar o nome atual (Membro ad hoc) para Revisor ad hoc. Dessa forma, ficaria assim:

- Revisor ad hoc >> Reviewer ad hoc >> R - **OK**

**Comment by AngelicaSAPaula** [comment]
Ok, podemos fazer desta maneira!
