### ISSUE TITLE
Incluir no formulário de novo usuário - título do periódico e issn

### ISSUE THREAD

**Issue by suelisuga** [bireme/lilacs-journal-selection#111]
Prezados,

Quando um editor solicita ativação de usuário no sistema de avaliação de periódicos há dificuldade de identificar o periódico que será avaliado.

Solicito inclusão dos campos no formulário de solicitação de usuário:
-Título do periódico
-ISSN

https://avaliacao.lilacs.bvsalud.org/public/account/new

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
@suelisuga o módulo de usuários do sistema não tem ligação com os protocolos. Essa relação só ocorre no momento em que o editor submete um periódico. Após a submissão, os membros da secretaria receberão um email com o link do periódico. Nesse link, terá toda a informação sobre o periódico submetido, inclusive o nome do editor que realizou a submissão.

**Comment by wilsonmoura** [comment]
@suelisuga o módulo de usuários do sistema não tem ligação com os periódicos. Essa relação só ocorre no momento em que o editor submete um periódico. Após a submissão, os membros da secretaria receberão um email com o link do periódico. Nesse link, terá toda a informação sobre o periódico submetido, inclusive o nome do editor que realizou a submissão.
