### ISSUE TITLE
Permissão de upload de mais documentos

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#118]
Dado o fato de muitas revistas terem submetido o excel com informações erradas e termos solicitado o envio de uma nova versão correta, seria possível abrir mais um campo para anexar esta documentação atualizada para que os avaliadores e membros do comitê possam ter acesso?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula testar no ambiente de homologação. Esse campo adicional para upload de documentos fica visível na página do periódico somente para o editor e quando o periódico está na primeira fase de avaliação (quando o editor envia os dados do periódico).

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura fiz a submissão de uma  nova revista como editor, aceitei como coordenação e voltei como editor e o campo de anexo de novos documentos não aparece disponível.

O ideal é que, tão breve seja aceito pela Coordenação, ele já tenha acesso, pois muitas vezes solicitamos o envio de nova documentação antes de enviar aos pareceristas e essa documentação é necessária para continuidade de qualquer atividade. Sem a documentação correta, não conseguimos dar prosseguimento à realização dos relatórios.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula conforme informado, esse campo adicional só fica disponível quando o periódico está na primeira fase de análise (aba Análise). É nessa fase que o editor precisa ser informado sobre eventuais erros na informação submetida. Dessa forma, o editor tem tempo para enviar a nova documentação, evitando assim que o periódico seja aceito com informações erradas.

**Comment by AngelicaSAPaula** [comment]
Ok, acabei de verificar este campo no formulário do Editor! Obrigada!
