### ISSUE TITLE
Alteração e-mail de usuário

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#121]
Recebi uma resposta de que o e-mail de um usuário mudou e gostaria de alterar no perfil dele, mas não consigo realizar isso pelo sistema.

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura continuo sem conseguir editar os endereços de e-mail dos usuários

**Comment by AngelicaSAPaula** [comment]
Ainda sem conseguir editar...

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula só está faltando atualizar o ambiente de produção.
