### ISSUE TITLE
Inabilitar botão de enviar avaliação 

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#122]
Wilson, conforme conversamos, favor inabilitar o botão de "Salvar e enviar" para o revisor ad hoc só poder clicar nele após dar um check na opção "Declaro não possuir nenhum vínculo ou interesse próprio na avaliação deste periódico.".

**Comment by wilsonmoura** [comment]
Realizado em 7f66ef138920e6774b210fb9d5a66e516077f855
