### ISSUE TITLE
Check-list aptidão (pré-avaliação)

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#129]
Seria possível criar um check-list que os editores devem preencher e somente se tiverem uma determinada pontuação é que a submissão de um novo periódico se torna possível / disponível?

O ideal é que este formulário ficasse na plataforma e fosse editável para que, futuramente, cada país possa adaptá-lo de acordo com seus critérios e que seja possível analisarmos todas as respostas (geração de relatório).

Gostaríamos de fazer algo parecido com este aqui: [https://www.readyforscopus.com/pt/].

Sendo possível esta implementação, criaremos o conteúdo das perguntas / respostas!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula favor informar o critério/pontuação para que a submissão de um novo periódico seja possível.

**Comment by AngelicaSAPaula** [comment]
Ele precisa responder "Sim" a todas as perguntas do formulário, exceto a "Mínimo de 45 artigos por ano": 

https://docs.google.com/forms/d/e/1FAIpQLSfDj2mEPa4bIBi41yY8Gs4qf0ZSeu-Ows7UNJqnWS725S3WdA/viewform

**Comment by wilsonmoura** [comment]
Após reunião, ficou decidido que manteremos o formulário do Google Forms, informando o link do sistema de avaliação por e-mail somente quando o editor responder corretamente as perguntas do formulário.
