### ISSUE TITLE
Permitir membros do comitê darem nota ao revisor

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#131]
Além das notas ao parecer, incluir um campo para pontuar o revisor (de 1 a 5).

A média de nota de cada parecerista deverá aparecer ao lado de seu nome na lista de usuários e precisará ser um filtro (classificação).

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula testar no ambiente de homologação. Com relação ao filtro, será implementado em #135

**Comment by AngelicaSAPaula** [comment]
Verifiquei que a média das notas já aparece na lista de usuários e o filtro por ordem crescente ou decrescente! Obrigada!
