### ISSUE TITLE
Histórico revisores

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#132]
É possível gerar um histórico de cada revisor com as seguintes informações:

• Revisões atualmente distribuídas
• Revisões terminadas
• Pedidos de revisão recusados (caso seja possível a implementação daquele issue de aceitação preliminar do convite de avaliação)
• Dias desde a última revisão atribuída
• Número médio de dias para completar a revisão

![image](https://user-images.githubusercontent.com/47643830/78811704-a5b43380-79a0-11ea-958a-009e4accf34b.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula os relatórios estão disponíveis no ambiente de homologação.

Com relação ao item "Pedidos de revisão recusados", atualizamos a issue #103 com uma sugestão de implementação que vai prover o metadado necessário para gerar esse relatório.
