### ISSUE TITLE
Novo formulário avaliação Revisores Ad Hoc

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#133]
Favor substituir o formulário existente para o que envio a seguir.

[modelo_form_parecerista_poscomite_final.docx](https://github.com/bireme/lilacs-journal-selection/files/4452059/modelo_form_parecerista_poscomite_final.docx)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula todo o formulário será substituído? Ou algumas perguntas serão mantidas/atualizadas? No caso do formulário ser totalmente substituído, as revisões anteriores serão perdidas. Caso contrário, para a implementação ser mais viável, preciso do mapeamento de campos para identificar aqueles que serão incluídos/mantidos/atualizados/removidos. Vale reforçar que campos removidos também removem a respectiva informação de revisões anteriores.

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura segue documento indicando o que é campo novo e o que já existe. Farei o download de todas as revisões realizadas no ano passado para não haver problemas! Existe a possibilidade de eu, enquanto coordenação, incluir novos documentos mesmo após o encerramento do processo? Assim, deixaria estas avaliações anexadas.
[modelo_form_parecerista_poscomite_final (1).docx](https://github.com/bireme/lilacs-journal-selection/files/4488558/modelo_form_parecerista_poscomite_final.1.docx)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula formulário atualizado no ambiente de homologação.

OBS: Como somente um campo foi removido, para não perder esse dado, ele permanece na visualização das revisões anteriores que possuem essa informação.
