### ISSUE TITLE
Revisão perguntas formulário avaliação comitê

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#134]
Favor adicionar o seguinte trecho nas perguntas 1 e 2 do formulário de avaliação do Comitê:

"**(qualidade de artigos, mérito científico, aspectos éticos, critérios de arbitragem e corpo editorial, difusão do periódico), aponte os mais relevantes.**"

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula texto atualizado no ambiente de homologação. Favor incluir as devidas traduções em https://avaliacao.lilacs.homolog.bvsalud.org/_trans/

**Comment by AngelicaSAPaula** [comment]
Traduções realizadas!
