### ISSUE TITLE
Filtro por média de notas das revisões adhoc

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/lilacs-journal-selection#135]

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula filtro implementado no ambiente de homologação.

**Comment by AngelicaSAPaula** [comment]
No caso deste filtro, não é possível selecionar, somente organizar por ordem decrescente ou crescente, certo?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula esse filtro organiza somente por ordem decrescente e crescente.
