### ISSUE TITLE
Visualização histórico avaliadores

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#136]
É possível que as informações do histórico dos avaliadores sejam "clicáveis" e nos apresentem dados mais detalhados? Por exemplo, ao clicar em revisões atribuídas, mostrar quais eram os periódicos.

Ainda, estas informações podem aparecer, também, na listagem de usuários e não só no momento da seleção deles dentro do processo de avaliação?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula Por limitações técnicas, não foi possível incluir os dados "clicáveis". Com relação aos relatórios adhoc, já estão disponível no ambiente de homologação.
