### ISSUE TITLE
Filtro avaliadores

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#137]
É possível incluir filtro de área e ordenação por nota no momento de selecionar o avaliador, dentro da avaliação do periódico? Em termos práticos, é nesse momento que necessitamos mais das informações detalhadas de cada um e os filtros fqacilitarão encontrar e indicar o avaliador correto.

![image](https://user-images.githubusercontent.com/47643830/81975267-23e9a280-95fd-11ea-91ba-582f1c04071c.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula filtro por área de atuação disponível para testes no ambiente de homologação. Com relação a ordenação por nota, só foi possível incluir essa opção. No entanto, como alternativa, ajustamos a lista em ordem decrescente de nota.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula o filtro por área de atuação está disponível para testes no ambiente de homologação. Com relação a ordenação por nota, não foi possível incluir esse recurso. No entanto, como alternativa, padronizamos a lista em ordem decrescente de nota.

**Comment by AngelicaSAPaula** [comment]
ok, filtro validado!
