### ISSUE TITLE
Motivos de recusa da avaliação

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#138]
Seria possível que os avaliadores, no momento que recusarem a avaliação, possam incluir o motivo? Seria uma caixa pop-up com itens pré-determinados e uma caixa aberta para "outro motivo".

Motivos:
• Fiz ou faço parte da equipe editorial
• Conheço os editores
• Estou aposentado (a)
• Muitas atividades no momento
• Outro motivo

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula as opções foram registradas no ambiente de homologação. Favor realizar as devidas traduções.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula as opções foram registradas no ambiente de homologação.

**Comment by AngelicaSAPaula** [comment]
No momento de selecionar um parecerista para fazer a avaliação, dá erro.

![image](https://user-images.githubusercontent.com/47643830/82928752-07345f80-9f59-11ea-8da8-fb975e7be550.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula favor testar novamente.

**Comment by AngelicaSAPaula** [comment]
Ok, agora consegui!

É possível que, ao escolher a opção "outro motivo" abra uma caixa para o parecerista escrever sua justificativa (não-obrigatório, ele pode escolher este motivo e não se justificar)?

**Comment by AngelicaSAPaula** [comment]
Acredito que, após a recusa, o periódico deva sair da lista do parecerista ou ele não possa visualizar os dados e documentação.

E que a Coordenação possa verificar o motivo da recusa ao lado do nome do parecerista na revisão do periódico

![image](https://user-images.githubusercontent.com/47643830/82942668-b16ab200-9f6e-11ea-83aa-d9641f24eec9.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula recurso disponível para testes no ambiente de homologação.

**Comment by AngelicaSAPaula** [comment]
Teste realizado e o recurso funciona adequadamente!
