### ISSUE TITLE
Campos repetidos

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#139]
Na página de visualização da Coordenação, os campos "Parecerista Ad Hoc" e "Membros revisores do Comitê" aparecem duplicados.

Entendo que são duas informações diferentes, mas seria possível juntá-las?

![image](https://user-images.githubusercontent.com/47643830/88086717-31239000-cb5e-11ea-8a8a-b594db2eeae1.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ocultamos a lista do cabeçalho somente nessa página, pois essa lista só vai exibir os pareceristas que enviaram as revisões. Na outra lista, mais abaixo, você tem a lista completa de revisões (recusadas, pendentes, enviadas, etc).
