### ISSUE TITLE
Filtro Pareceristas Ad Hoc

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#140]
Seria possível ordenar a lista de pareceristas ad hoc por ordem alfabética ou colocar mais opções de filtro (nome, email, instituição)?

Refiro-me à lista que abre em pop-up para o membro da Coordenação!

![image](https://user-images.githubusercontent.com/47643830/88087056-b7d86d00-cb5e-11ea-8847-152d70a4b6f8.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula conforme conversamos em reunião, serão adicionados os filtros por nome e email.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula recurso disponível para testes no ambiente de homologação.

**Comment by AngelicaSAPaula** [comment]
Ok, filtros implementados! conforme solicitado!
