### ISSUE TITLE
Tradução de labels

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#141]
Não encontro, nem em produção nem em homolog, os textos em inglês referentes à aceitação ou recusa prévia do avaliador e aos filtros (rating).

![image](https://user-images.githubusercontent.com/47643830/88108643-8c19af00-cb7f-11ea-9441-dc47867f4995.png)

![image](https://user-images.githubusercontent.com/47643830/88108771-c97e3c80-cb7f-11ea-8e02-a1fbe40940ec.png)

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura todas as traduções foram realizadas no ambiente homolog!

**Comment by AngelicaSAPaula** [comment]
Labels traduzidas no ambiente de homologação

**Comment by wilsonmoura** [comment]
Traduções aplicadas no ambiente de produção.
