### ISSUE TITLE
Demora no carregamento das páginas

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#144]
Boa tarde!

Todas as ações que realizo na plataforma demoram muito para carregar. Já conferi e não se trata da velocidade da minha conexão.

Constantemente aparece a seguinte tela:

![demora](https://user-images.githubusercontent.com/47643830/96291565-9a306d80-0fbe-11eb-857b-dd671b51a100.PNG)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula devido ao aumento do número de usuários, tivemos que modificar a forma de visualização do histórico dos pareceristas. Já atualizamos o ambiente de produção. Favor testar e verificar se a lentidão ainda persiste.

**Comment by AngelicaSAPaula** [comment]
Boa tarde!

A visualização do histórico ficou bem melhor abrindo numa caixa pop-up e a lentidão diminuiu consideravelmente.

Muito obrigada!
