### ISSUE TITLE
Melhorias na visualização dos pareceristas

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#147]
É possível incluir, ao lado da coluna da data de solicitação de avaliação, a data de envio do lembrete?

![image](https://user-images.githubusercontent.com/47643830/96292849-37d86c80-0fc0-11eb-8b0d-e82f4181e010.png)

Além disso, é possível trocar a coluna de "Instituição" pelo Currículo Lattes?

Pode-se incluir uma caixa de seleção ao lado do nome dos pareceristas, caso eu queira excluir mais de um de uma vez?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de homologação atualizado. Favor testar.

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura testes realizados e está ok!

Ainda, durante o processo sentimos a necessidade da indicação da data que o parecerista respondeu a avaliação. É possível uma coluna a mais?

Aproveitando, verifiquei que a seção de Membros do Comitê, a coluna que mostra o CV está com a etiqueta de "Instituição". Na verdade, para os membros do Comitê, ambas as informações (CV e Instituição) são desnecessárias, caso queira retirá-las.

![image](https://user-images.githubusercontent.com/47643830/105073376-c64c0680-5a65-11eb-9ff7-fef159f444fa.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de homologação atualizado. Favor testar.

A data de envio das revisões não existia na base de dados. Ou seja, essa informação só será exibida nas próximas revisões.
