### ISSUE TITLE
Mensagem página inicial

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#148]
É possível deixar uma mensagem fixa na página inicial de que a submissão pela plataforma é só para periódicos brasileiros e que só fica disponível no mês de agosto? É possível, ainda, não permitir criação de usuários (quando o próprio cria uma conta) fora deste período?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula poderia enviar um print como exemplo do local onde devemos exibir essa mensagem? Se possível, informar também o texto que será exibido.

**Comment by AngelicaSAPaula** [comment]
No momento em que o usuário for criar um login, aparecer a mensagem ao final:

"Estou ciente de que, no momento, a submissão é possível somente para periódicos brasileiros e estará disponível apenas no período de 01 a 31 de julho."

![image](https://user-images.githubusercontent.com/47643830/105074251-e03a1900-5a66-11eb-8de5-92792fa893a2.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de homologação atualizado. Favor testar.

Para informar o período de submissão de periódicos, acessar o menu `Gestão do Sistema >> Configurações >> Submission Period`
