### ISSUE TITLE
E-mails não estão sendo entregues / SPAM

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#150]
Percebemos que quase não recebemos resposta dos avaliadores (mais de 240) convidados, e enviamos um e-mail de fora do sistema. 

Então, a grande maioria afirmou que não havia recebido nem o convite, nem o lembrete, e os pouquíssimos que receberam, informaram que estava na caixa de spam.

Há algo que se possa fazer para solucionar isso?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula a principal causa disso é o fato de que os domínios de emails que pertencem à BIREME estarem frequentemente nas blacklists. Esse é um problema recorrente e antigo que temos no envio de emails. Existem algumas ações que já tomamos que diminuem a chance de ocorrer problemas no envio de mensagens, pois isso já ocorreu com outras aplicações. Mas isso não garante o funcionamento 100% desse recurso. Na maioria dos casos, por serem mensagens automáticas sempre com a mesma estrutura e geralmente com links no corpo do email, normalmente são classificadas como SPAM. Por fim, para evitar possíveis contratempos com o envio de mensagens, a orientação é verificar a caixa de spam e remover essa marcação para garantir o recebimento de futuras mensagens.
