### ISSUE TITLE
Criar botão "aceitar" para revisores ad hoc

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#151]
Este ano, os revisores sentiram falta de ter um local para sinalikzarem o aceite do convite.

Seria possível criar um botão para isso, igual ao de recusar?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de homologação atualizado. Favor testar.

Para melhorar a usabilidade, trocamos o botão "rejeitar revisão" pelo botão "convite para revisar periódico". Ao clicar nesse botão, o parecerista terá a opção de aceitar/rejeitar o convite para revisar o respectivo periódico.
