### ISSUE TITLE
Revisores não conseguem salvar formulário preenchido

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#152]
Tenho recebido diversos emails dos revisores, dizendo que preencheram o formulário na plataforma de avaliação, clicaram em "Salvar e enviar" e o sistema não salvou... 

Qdo entro com o perfil "Coordenação" aparece que eles não responderam e quando eles entram na plataforma, também aparece como se eles ainda não tivessem avaliado.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula fiz testes nos ambientes de homologação e também na produção. Em ambos os testes, o envio da revisão funcionou normalmente. Precisamos de alguma evidência para analisar com mais detalhes. Peço que também realize alguns testes (homologação e produção) para que possamos identificar um possível padrão no fluxo de envio das revisões que permita uma análise mais detalhada do problema.

**Comment by AngelicaSAPaula** [comment]
Também não consegui reproduzir o erro, mas quase 10 revisores reportaram isso. Vou verificar se este erro se dá quando mudamos de navegador.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula vamos encerrar esse issue e reabrir caso o problema ocorra novamente.
