### ISSUE TITLE
Erro ao anexar arquivo

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#154]
Estou tentando incluir um novo anexo na revista Academus, mas dá o seguinte erro:

![image](https://user-images.githubusercontent.com/47643830/100907933-abb7d100-34a9-11eb-9557-351490025f3b.png)

Estou tentando anexar como tipo "Outro" um pdf de 2,01 MB

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula revisei as configurações do sistema e verifiquei que o limite máximo de upload é de 2MB.
