### ISSUE TITLE
Erro ao salvar rascunho

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#155]
Com perfil de membro de comitê, após preencher o formulário de avaliação e tentar salvar como rascunho, aparece a seguinte mensagem:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

![image](https://user-images.githubusercontent.com/47643830/102559385-7d8fdf00-40ae-11eb-8bfc-27ad4bd5b822.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de produção atualizado. Favor testar.

**Comment by AngelicaSAPaula** [comment]
Ao início de 2021, este problema foi resolvido.
