### ISSUE TITLE
Revisores que responderam não aparecem aos membros do comitê

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#156]
Apesar de 5 avaliações recebidas, só aparece um revisor para o membro de equipe avaliar:

![image](https://user-images.githubusercontent.com/47643830/102559509-cc3d7900-40ae-11eb-83f0-02c7395a31f6.png)

**Comment by wilsonmoura** [comment]
Resolvido em 1d9c07fcb8c9cd0bdf9157b8b53f62a2e6a6c3f6

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de produção atualizado. Favor testar.

**Comment by AngelicaSAPaula** [comment]
Ao início de 2021, este problema foi resolvido.
