### ISSUE TITLE
Não é possível verificar a avaliação dos membros do comitê aos revisores

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#157]
Quando abrimos a revisão dos membros de comitê, não conseguimos ver qual foi a nota atribuída aos revisores respondentes

![image](https://user-images.githubusercontent.com/47643830/102626147-32fd7980-4125-11eb-8e95-8ca87c091e1d.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de produção atualizado. Favor testar.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de produção atualizado. Favor testar.

**Comment by AngelicaSAPaula** [comment]
Visualização já é possível
