### ISSUE TITLE
Correção formulário pareceristas

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#159]
@wilsonmoura, fizemos uma revisão do questionário aos pareceristas.

As correções / modificações eu já realizei em https://avaliacao.lilacs.homolog.bvsalud.org/_trans/. É necessário fazer, também, na produção?

No entanto, existem 2 perguntas que precisam ser retiradas:

- k) Existem indicadores e mecanismos editoriais para eliminação de erros de normalização (por exemplo, seções incorretamente numeradas, tabelas/quadros erroneamente nomeados)?

- A área de orientação profissional tem suficiente densidade que justifique a entrada do periódico na LILACS?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula você fez os ajuste no local correto (homolog). Já realizei os ajustes solicitados no formulário. Também já solicitei ao ITI a atualização do ambiente de produção.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de produção atualizado. Favor validar.

**Comment by AngelicaSAPaula** [comment]
Formulário conferido!
