### ISSUE TITLE
Alteração de documentado enviado por editor 

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#160]
@wilsonmoura um editor anexou o documento errado no momento da submissão (https://avaliacao.lilacs.bvsalud.org/journal/164). É possível alterá-lo? 

[Avaliacao_LILACS_2021.xls](https://github.com/bireme/lilacs-journal-selection/files/6889438/Avaliacao_LILACS_2021.xls)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula os arquivos enviados são obrigatórios e não podem ser removidos. Sendo assim, implementei uma funcionalidade para incluir/remover documentos adicionais (somente secretaria). Basta pedir para o usuário enviar para a secretaria o documento correto e incluir no respectivo registro. Favor testar no ambiente de homolog.

![screenshot-avaliacao lilacs homolog bvsalud org-2021 07 29-21_37_05](https://user-images.githubusercontent.com/3779520/127582714-ba6e40cc-41a6-44e9-9218-cbcd5f17ce68.png)

**Comment by AngelicaSAPaula** [comment]
Oi @wilsonmoura! Esta funcionalidade já existe, e é por onde incluirmos os documentos de endogenia e relatório de formato.

Na verdade, eu não expliquei direito acima. Gostaria de incluir esta documentação logo na primeira etapa, antes da avaliação inicial, onde aceitamos ou rejeitamos a submissão!

Isto se fará necessário, inclusive, porque agora o relatório de formato será realizado logo no início e isso determinará a aceitação ou rejeição da submissão!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula acho melhor a gente se reunir para discutir sobre isso pois, mesmo lendo o seu último comentário, eu ainda não entendi bem onde colocar/substituir esse documento. Me avise assim que estiver disponível.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar. Desconsiderar último comentário.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados no ambiente de homolog. Favor validar.

**Comment by AngelicaSAPaula** [comment]
Ajustes conferidos e tudo funcionando corretamente!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de produção atualizado. Favor validar.

**Comment by AngelicaSAPaula** [comment]
Ajustes conferidos e tudo funcionando corretamente!
