### ISSUE TITLE
Atualizar ambiente de produção - tradução de labels

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#161]
Wilson, acabei de reparar que ainda existiam labels em inglês e já realizei a tradução no ambiente de homologação.

![image](https://user-images.githubusercontent.com/47643830/127936141-8a985d3c-7677-4995-af33-206fe1a8a53d.png)

![image](https://user-images.githubusercontent.com/47643830/127936191-863360a6-4d4e-427d-8f1e-fe6ad6fa73b9.png)

**Comment by wilsonmoura** [comment]
Realizado em 28abfc1b393f3fbeb7730349c8645ba8952116b1

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ambiente de produção atualizado. Favor validar.

**Comment by AngelicaSAPaula** [comment]
Atualizações ok!
