### ISSUE TITLE
Remoção de informação / coluna

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#162]
Por gentileza, retirar a coluna "e-mail" no campo de pareceristas ad-hoc e membros revisores do comitê.

![image](https://user-images.githubusercontent.com/47643830/127936684-d8ad7545-9473-4130-af02-da6f5b290591.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de homolog.

**Comment by AngelicaSAPaula** [comment]
Ajustes ok!
