### ISSUE TITLE
Inversão ordem de informação

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#163]
Por gentileza, trocar a ordem das colunas "Review submission date" com "Alert delivery date"

![image](https://user-images.githubusercontent.com/47643830/127936789-00b430e8-c45b-43f6-bf72-f47736910149.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de homolog.

**Comment by AngelicaSAPaula** [comment]
Ajustes ok!
