### ISSUE TITLE
Alteração texto mensagens emails

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#164]
Por gentileza, seria possível atualizar a instância produção? Realizei, em homolog, a atualização das mensagens de emails.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula verifiquei no ambiente de homolog e não consta nenhuma atualização das traduções. Favor confirmar se fez as atualizações em https://avaliacao.lilacs.homolog.bvsalud.org/_trans/ (lembrando que deve estar logado para acessar esse link).

**Comment by AngelicaSAPaula** [comment]
Realizei as modificações em https://avaliacao.lilacs.homolog.bvsalud.org/admin/mail

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula Perdão, acabei confundindo as coisas, pois não me atentei qual texto estava se referindo. Nesse caso, as traduções de mensagens de email e texto de ajuda podem ser modificadas diretamente no ambiente de produção. A exceção são as traduções de rótulos, que devem ser feitas em https://avaliacao.lilacs.homolog.bvsalud.org/_trans/ e posteriormente solicitar transferência para o ambiente de produção.
