### ISSUE TITLE
Recebimento de e-mail

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#166]
Boa tarde!

É possível receber emails a cada vez que um parecerista aceitar ou rejeitar o convite para avaliação?

Grata!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula é possível sim. Nesse caso, o sistema enviará mensagens diretamente aos membros da secretaria.

**Comment by AngelicaSAPaula** [comment]
ok, de acordo!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de homolog.

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura realizei o teste, mas não recebi qualquer email

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula falta incluir o texto das mensagens no menu `Gestão do Sistema >> Mensagens de e-mail`.
Nesse menu, o ID das novas mensagens são 16 (aceitação do convite para revisão) e 17 (rejeição do convite para revisão).

**Comment by AngelicaSAPaula** [comment]
Mensagens atualizadas!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula conseguiu testar o envio dos novos e-mails após atualizar as mensagens? Está tudo funcionando bem? Favor informar caso seja necessário mais algum ajuste. Caso contrário, pode encerrar esse issue.
