### ISSUE TITLE
Recebimento email ações dentro do periódico

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#168]
Por gentileza, é possível recebermos email cada vez que o editor, parecerista ou membro do comitê realizarem ações dentro do sistema?

Por exemplo, hoje uma revista aprovada com restrições em 2019 enviou, via sistema, as correções propostas e só vi porque estamos em período de avaliação e, por isso, acesso a plataforma todos os dias. Se não fosse isso, não saberia que tem ações a serem realizadas

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula no caso dessa ação específica, o sistema já está configurado para enviar uma mensagem para a secretaria quando o editor submete as recomendações pendentes. A mensagem referente a essa ação está disponível no menu `Gestão do Sistema >> Mensagens de e-mail` (ID 6). Favor realizar teste na homolog para confirmar o envio dessa mensagem. Caso esteja funcionando corretamente, provavelmente essa mensagem pode ter sido direcionado para a caixa de spam ou também pode ter ocorrido algum problema pontual no servidor SMTP responsável pelo envio de e-mails.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula no caso dessa ação específica, o sistema já está configurado para enviar uma mensagem para a secretaria quando o editor submete as recomendações pendentes. A mensagem referente a essa ação está disponível no menu `Gestão do Sistema >> Mensagens de e-mail` (ID 6). Favor realizar teste na homolog para confirmar o envio dessa mensagem. Caso esteja funcionando corretamente, provavelmente essa mensagem pode ter sido direcionada para a caixa de spam ou também pode ter ocorrido algum problema pontual no servidor SMTP responsável pelo envio de e-mails.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula vamos encerrar esse issue e reabrir caso necessário.
