### ISSUE TITLE
Retirada de obrigatoriedade de anexos

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#169]
Este ano juntamos alguns relatórios e, por isso, não estou conseguindo ir para a aba "Reunião", pois indica que faltam documentos a serem anexados. Seria possível retirar a obrigatoriedade deles, ou deixar obrigatórios somente formato e endogenia?

**Comment by AngelicaSAPaula** [comment]
Por gentileza, necessitamos desta atualização para envio dos relatórios finais de cada revista. Muito obrigada!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de homolog.
