### ISSUE TITLE
Botão para Home

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#171]
Seria possível ao clicar no ícone da LILACS voltar para a página inicial?

![image](https://user-images.githubusercontent.com/47643830/167942503-3c78bb23-edf4-4465-ae1d-d6181ef6b63a.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de homolog.

**Comment by AngelicaSAPaula** [comment]
Testes realizados e ok!!!
