### ISSUE TITLE
Identificação de usuário criado

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#172]
É possível que no email recebido quando um novo usuário se cadastrada na plataforma, seja identificadoque usuário é este? 

________________________________________________________________________
bir.lilacs.selecao@paho.org
Um novo usuário se cadastrou no Portal de Avaliação de Periódicos LILACS.

Acesse o sistema para ativar este cadastro e definir os papéis adequados.

Atenciosamente,

SELEÇÃO DE PERIÓDICOS LILACS BRASIL
BIREME | Departamento de Evidência e Inteligência para Ação em Saúde
OPAS/OMS
http://red.bvsalud.org/lilacs/es/editor/

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Para exibir o nome de usuário, basta incluir o token `%username%` no corpo da mensagem de e-mail. Favor validar no ambiente de homolog.

**Comment by AngelicaSAPaula** [comment]
Criei um novo usuário no ambiente de homolog e recebi o email corretamente!
