### ISSUE TITLE
Alteração de links

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#173]
Favor alterar o link de **Dados de Submissão** para https://docs.google.com/spreadsheets/d/14LDlAUsav4usmdguIzi8Yezd52Up7JYy/edit?usp=sharing&ouid=111538096332496031608&rtpof=true&sd=true

![image](https://user-images.githubusercontent.com/47643830/181806562-45157834-8c25-41b5-bb53-6f112add0287.png)

Já na opção "**[Confirmo que realizei a autoavaliação do periódico e ele está apto a ser submetido para avaliação]**" colocar link https://bit.ly/checklist_lilacs

![image](https://user-images.githubusercontent.com/47643830/181806868-2290079b-3134-4003-bd22-031ab7d0fd96.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de homolog.

**Comment by AngelicaSAPaula** [comment]
Links corrigidos!

**Comment by AngelicaSAPaula** [comment]
Acabei de notar que na página de criação de novo login é necessário trocar o link também para <https://bit.ly/checklist_lilacs>

![image](https://user-images.githubusercontent.com/47643830/182445590-753a4e21-a183-457b-a8ab-be5ad3b1cef3.png)

Ainda, em homolog, nesta página aparece uma mensagem do período de submissão, mas não aparece na versão final.

![image](https://user-images.githubusercontent.com/47643830/182445787-db683537-ab3b-4edb-9fa6-2cc34f2c528e.png)

A mensagem pode ser a seguinte: _Estou ciente de que esta plataforma é exclusiva para o processo de seleção de avaliação de periódicos brasileiros e o período de submissão é somente durante o mês de **JULHO** de cada ano._

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. A mensagem do período de submissão só será exibida se o período de submissão for devidamente configurado no menu `Gestão do Sistema >> Configurações`. Essa mensagem foi definida dessa forma em #148, justamente para evitar o nome fixo do mês referente ao período de submissão, pois existe a possibilidade desse período mudar em outras ocasiões.
