### ISSUE TITLE
Novas condições para revisores ad hoc

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#174]
Por gentileza, colocar mais duas caixas de seleção ao final do relatório dos pareceristas ad hoc:

![Captura de tela 2022-08-25 210119](https://user-images.githubusercontent.com/47643830/186791644-fa6ea894-2344-4217-97c3-eace6ea4c1ad.png)

**- [ ] Estou de acordo com que o editor saiba minha identidade.**
**- [ ] Estou de acordo em ter minha avaliação divulgada e identificada publicamente.**

As opções não são obrigatórias de serem marcadas.

**Comment by suelisuga** [comment]
@wilsonmoura atualização das condições:

[ ] Estou de acordo em ter minha identidade divulgada ao editor do periódico avaliado.
[ ] Estou de acordo em ter minha avaliação divulgada publicamente, mas sem a identificação.
[ ] Estou de acordo em ter minha avaliação divulgada e identificada publicamente.

As opções não são obrigatórias de serem marcadas.

Já validado com Angélica.

Obrigada!

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula @suelisuga ajustes realizados no ambiente de homolog. Favor validar.

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura a seleção das condições está funcionando perfeitamente. No entanto, como eu consigo visualizar, enquanto secretaria, as condições que eles assinalaram? Quando entro no questionário respondido estas opções não aparecem

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados no ambiente de homolog. Favor validar.

**Comment by AngelicaSAPaula** [comment]
Testes realizados e ok! Muito obrigada :)
