### ISSUE TITLE
Correção e tradução 

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#175]
Preciso corrigir e atualizar algumas mensagens / labels, mas não estou conseguindo acesso no ambiente de produção. 

![image](https://user-images.githubusercontent.com/47643830/188764512-f219eb45-09c1-42f0-8d5e-4cbe3519e1a9.png)

Devo fazer no homolog?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula exatamente. Os ajustes de textos devem ser feitos em homolog. Assim que finalizar, vamos atualizar o ambiente de produção.

**Comment by AngelicaSAPaula** [comment]
Traduções / correções realizadas no ambiente homolog. Favor atualizar o ambiente de produção!
