### ISSUE TITLE
Alteração visualização Revisores ad hoc

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#177]
Por gentileza, é possível realizar a seguinte modificação na visualização de usuários com perfil revisor?

- retirar a parte de Parecer Final na visualização do periódico (permite envio de comentários antes de aceitar a revisão; deixar habilitado somente após o aceite do convite)

![image](https://user-images.githubusercontent.com/47643830/188765645-41914f40-6b17-4991-804e-7a7e8560ce78.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados no ambiente de homolog. Favor validar.
