### ISSUE TITLE
Endogenia - Autores por grupo

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/lilacs-journal-selection#180]
https://public.tableau.com/app/profile/bireme/viz/endogenia-lilacs-autores-2022/Autores

@AngelicaSAPaula, segue uma pequena lista com o nome dos autores que precisa ser verificado. 

Eliana Meira Melhado
Eliana Meire Melhado
Leonardo R Leira Pereira
Leonardo Regis Leira Pereira
Leopoldo Mandic Ferreira Furtado
Leopoldo Mandic Furtado
Lucas M Okumura
Lucas Miyake Okumura
Mariana M. Fachi
Mariana Millan Fachi
Milena M. Xavier
Milene Maria Xavier Veloso

**Comment by AngelicaSAPaula** [comment]
[Endogenia_2022_revisado.xlsx](https://github.com/bireme/lilacs-journal-selection/files/9804793/Endogenia_2022_revisado.xlsx)

Planilha conferida!

Milena M. Xavier e Milene Maria Xavier Veloso são autoras distintas

**Comment by anakatiacamilo** [comment]
@AngelicaSAPaula, atualizei dos dois dashboard de endogenia, por favor, verificar e qualquer ajuste me informar. 

Por favor, substituir o seu arquivo original por esta se possivel ele esta com as alterações necessarias para o processamento.

[endogenia-lilacs-20221018.xlsx](https://github.com/bireme/lilacs-journal-selection/files/9812771/endogenia-lilacs-20221018.xlsx)
