### ISSUE TITLE
Informações não salvas

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#181]
@wilsonmoura, percebi que se a página fica inativa por alguns minutos, é necessário se logar novamente para que qualquer alteração seja armazenada corretamente. Ou seja, se deixo a página aberta, mas não interajo por determinado tempo, qdo preencho algo e clico em Salvar, o site volta pra página inicial de login e o conteúdo acaba sendo perdido. 

Acredito que este isto que tenha acontecido com os pareceristas que relataram ter perdido o conteúdo que já havia sido preenchido.

Caso seja este mesmo o problema, é possível aumentar (ou eliminar) o tempo que se pode ficar com a página aberta e inativa?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustamos o tempo limite de cada sessão para 2 dias.
