### ISSUE TITLE
Aperfeiçoamento filtros página "Usuários"

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#183]
Seria possível incluir mais opções nos filtros dos usuários?

Preciso selecionar os usuários que estão sem papel estabelecido (adicionar esta opção em 'perfis') e criar um filtro de status, para eu ativar os que ainda estão inativos. Atualmente, preciso dar ctrl+f ou ir baixando a barra de rolagem para identificar estes usuários, o que me toma muito tempo e, cada alteração que eu realizo, a página é atualizada e volta pro topo, o que faz com que eu tenha que decorar qual era o usuário que estava editando para voltar nele.

![image](https://github.com/bireme/lilacs-journal-selection/assets/47643830/c1f120b7-8e85-4902-8a7a-9a778109af26)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de testes.

**Comment by AngelicaSAPaula** [comment]
O filtro para "nenhum" está funcionando corretamente. Existe a possibilidade de fazer o mesmo com "Ativo" e "Inativo"?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula essa nova opção atende a mesma necessidade sem criar um novo filtro, pois normalmente usuários inativos não possuem perfis associados. Mas se esse filtro for realmente necessário, favor confirmar para que possamos encaminhar essa demanda. Vale ressaltar que, como existe pouco espaço disponível no bloco de filtros e caixa de pesquisa, vamos ter que repensar e redistribuir os filtros nessa página.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula essa nova opção atende a mesma necessidade sem criar um novo filtro, pois normalmente usuários inativos não possuem perfis associados. Mas se mesmo assim esse filtro ainda for necessário, favor confirmar para que possamos encaminhar essa demanda. Vale ressaltar que, como existe pouco espaço disponível no bloco de filtros e caixa de pesquisa, vamos ter que repensar e redistribuir os filtros nessa página.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula essa nova opção atende a mesma necessidade sem criar um novo filtro, pois normalmente usuários inativos não possuem perfis associados. Mas se mesmo assim esse filtro ainda for realmente necessário, favor confirmar para que possamos encaminhar essa demanda. Vale ressaltar que, como existe pouco espaço disponível no bloco de filtros e caixa de pesquisa, vamos ter que repensar e redistribuir os filtros nessa página.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de testes.
