### ISSUE TITLE
Alterar link de label

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#184]
Por gentileza, alterar o link debaixo da condição "[Confirmo que realizei a autoavaliação do periódico e ele está apto a ser submetido para avaliação](https://bit.ly/checklist_lilacs)", na aba "Revisão", para:

► https://bit.ly/aptidaoLilacs

![image](https://github.com/bireme/lilacs-journal-selection/assets/47643830/b8007ceb-197a-481b-8505-4dc925132133)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados.

**Comment by AngelicaSAPaula** [comment]
Por gentileza, precisas corrigir o link na página de criação de usuário:
https://avaliacao.lilacs.bvsalud.org/public/account/new
![image](https://github.com/bireme/lilacs-journal-selection/assets/47643830/181cae87-2dee-44ec-97ba-4a4cef226d44)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados conforme solicitado.
