### ISSUE TITLE
Tornar campos obrigatórios

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#185]
Em "Nova Submissão", na aba "Informações do periódico" tornar os campos 'ISSN' e 'ISSN Online' obrigatórios (deixá-los destacados em vermelho).

![image](https://github.com/bireme/lilacs-journal-selection/assets/47643830/ec4c7036-5775-4c55-81c6-5abfa8d3ec14)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados.
