### ISSUE TITLE
Se logar com e-mail

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#187]
Quando crio um novo usuário e mando o convite para ser editor, ele consegue gerar uma nova senha com o endereço de e-mail, mas para se conectar, é necessário o login. No entanto, ele ainda não tem esta informação neste momento do fluxo de avaliação.

Por isso, é possível permitir que o login seja realizado com o endereço de e-mail ao invés do usuário?

_____________________________________________
De: Paulo Caramelli
Enviado: terça-feira, 31 de outubro de 2023 16:16
Para: #BIR:Lilacs Selecao <bir.lilacs.selecao@paho.org>
Assunto: Re: [LILACS] Convite para avaliação de mérito científico de periódico para base de dados LILACS
 
Prezada Sra. Angélica, boa tarde!

Agradeço o convite, porém estou com grande sobrecarga de atividades e por este motivo não poderei aceitar. Tentei fazer essa indicação pelo sistema, seguindo as orientações que recebi. No entanto, consigo definir apenas minha senha, não meu login. Achei que era meu email, mas não funcionou. Por este motivo, indico minha indisponibilidade por meio deste email.

Cordialmente,

Prof. Paulo Caramelli
Professor Titular
Departamento de Clínica Médica - Neurologia
Faculdade de Medicina da Universidade Federal de Minas Gerais
Av. Prof. Alfredo Balena, 190 - Sala 246
30130-100, Belo Horizonte (MG) - Brasil

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor validar no ambiente de testes.

**Comment by AngelicaSAPaula** [comment]
Consegui me logar corretamente com o e-mail!
