### ISSUE TITLE
Atualização de links na página de submissão

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#190]
Boa noite!

Na aba "Anexo de Arquivos" qdo os editores estão submetendo um novo periódico, por gentileza, alterar o link de "Dados de Submissão" para: https://docs.google.com/spreadsheets/d/1vjV17vq5ZTFvAham-nLfb39tOCV0DEhb/edit?usp=sharing&ouid=111538096332496031608&rtpof=true&sd=true.

![image](https://github.com/bireme/lilacs-journal-selection/assets/47643830/04fea9d5-637e-4bbb-9f82-ff54e44e6648)

Já na aba "Revisão", ao final da página, na seção "Condições", alterar o link do primeiro item ([Confirmo que realizei a autoavaliação do periódico e ele está apto a ser submetido para avaliação) para: https://docs.google.com/forms/d/e/1FAIpQLSdwFMnOwGn-454WDrlpJ3lwEcmxYnj-1_1C_mxVqFRpBltK0Q/viewform.

![image](https://github.com/bireme/lilacs-journal-selection/assets/47643830/dc914480-344a-4271-85a0-88fb103b3ad3)

Na página de criação de novo login é necessário trocar o link também para https://docs.google.com/forms/d/e/1FAIpQLSdwFMnOwGn-454WDrlpJ3lwEcmxYnj-1_1C_mxVqFRpBltK0Q/viewform

![image](https://github.com/bireme/lilacs-journal-selection/assets/47643830/795f21e5-ef5d-4800-ab1d-f552283ee7a9)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula ajustes realizados. Favor solicitar atualização dos ambientes de testes e produção.

**Comment by AngelicaSAPaula** [comment]
Precisarei de uma nova correção do link "Dados de Submissão" > https://docs.google.com/spreadsheets/d/1pH7qe7t7haJSFk40SOmpcispkbNeZkt9/edit?usp=sharing&ouid=111538096332496031608&rtpof=true&sd=true

Aproveitando, como faço a solicitação da atualização dos ambientes de teste e produção?

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula link atualizado conforme solicitado. Favor solicitar atualização dos ambientes de testes e produção. Essa solicitação deve ser feita para o Marco ou Jocevaldo via OCOMON. Basta informar a URL de cada ambiente e solicitar a execução do comando abaixo no diretório de instalação do projeto:

    $ sudo make update
