### ISSUE TITLE
Metadados do formulario de submissão de periódicos à avaliação LILACS

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/lilacs-journal-selection#20]
Segue documento com os metadados: [Download](https://github.com/bireme/lilacs-journal-selection/files/3228964/metadados-selecao-periodicos_sugestoes.docx)

**Comment by wilsonmoura** [comment]
Criar entidades:
- Fascículo
- Tipo de Publicação
- Idioma
- Área Temática
- Especilidade

**Comment by renatomurasaki** [comment]
@wilsonmoura verificar a compatibilidade / alinhamento destes metadados com a base de dados Title. Há um potencial de alimentar a base Title após fluxo da submissão da LILACS.
