### ISSUE TITLE
Ajustar PDF de visualização dos metadados de submissão dos periódicos

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/lilacs-journal-selection#26]

**Comment by wilsonmoura** [comment]
Arquivo: [showPdf.html.twig](https://github.com/bireme/lilacs-journal-selection/blob/master/symphony/src/Proethos2/CoreBundle/Resources/views/NewSubmission/showPdf.html.twig)

**Comment by wilsonmoura** [comment]
@suelisuga conforme conversamos, fico no aguardo da sugestão de cabeçalho para exibir nos PDFs gerados com os metadados dos periódicos.

**Comment by suelisuga** [comment]
Wilson,

Segue sugestão de título do documento:

**XX** Reunião do Comitê de Avaliação e Seleção de Periódicos LILACS Brasil **2019**

O que deixei em negrito deve mudar a cada novo processo (considerando que ele é anual).

Obrigada!
Sueli
