### ISSUE TITLE
Metadados do formulário de revisão enviado pelos membros ad-hoc

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/lilacs-journal-selection#35]

**Comment by AngelicaSAPaula** [comment]
Segue modelo! 
[[baixar e preencher] Formulário de avaliação de mérito científico - Doxa Revista Brasileira de Psicologia e Educação.docx](https://github.com/bireme/lilacs-journal-selection/files/3359553/baixar.e.preencher.Formulario.de.avaliacao.de.merito.cientifico.-.Doxa.Revista.Brasileira.de.Psicologia.e.Educacao.docx)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula existe algum campo obrigatório nesse formulário?

**Comment by AngelicaSAPaula** [comment]
Os revisores precisam responder todas as questões
