### ISSUE TITLE
Metadados do formulário de revisão enviado pelos membros do comitê

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/lilacs-journal-selection#36]

**Comment by AngelicaSAPaula** [comment]
Wilson, segue modelo.
[form_comite_dialogos_junguianos.docx](https://github.com/bireme/lilacs-journal-selection/files/3359544/form_comite_dialogos_junguianos.docx)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula existe algum campo obrigatório nesse formulário?

**Comment by AngelicaSAPaula** [comment]
Os membros precisam responder todas as questões

**Comment by wilsonmoura** [comment]
Resolvido em aacc8a6411bede681c0d323febe3f7f1db86e27d

**Comment by AngelicaSAPaula** [comment]
Estou reabrindo este chamado para verificar a possibilidade de inclusão de uma questão avaliando os pareceristas ad hoc respondentes, conforme modelo envio acima, em docx.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula testar no ambiente de homologação. Favor incluir também as devidas traduções.

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura realizei o teste e aparece a seção para avaliação dos pareceristas! Vc poderia me indicar o link para eu realizar as traduções?

Onde conseguiremos consultar estas notas dos pareceristas? Quando entro no perfil de coordenação e vejo o relatório das respostas do membro do comitê, a pontuação não aparece

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula recomendamos abrir uma nova issue para informar o local de exibição da nota do parecerista, informando também se será exibida a soma ou a média das notas.

Com relação às traduções, elas são feitas acessando a URL abaixo:

https://avaliacao.lilacs.homolog.bvsalud.org/_trans/

**Comment by AngelicaSAPaula** [comment]
Ok, abrirei novo issue! Obrigada!
