### ISSUE TITLE
Criar etapa para avaliação final do periódico

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/lilacs-journal-selection#46]
Nome da etapa: **Avaliação final**

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula o assunto e a mensagem serão iguais ao email enviado ao finalizar o processo pela primeira vez? Caso contrário, poderia enviar uma sugestão de assunto da mensagem que será enviada ao finalizar definitivamente a avaliação do periódico?

**Comment by AngelicaSAPaula** [comment]
Caso não haja a opção de um tipo de e-mail para cada opção de decisão final, sim, o assunto será o mesmo!

**Comment by wilsonmoura** [comment]
Só existe um tipo de email, pois a decisão é informada no relatório final enviado em anexo na mensagem.
