### ISSUE TITLE
Criar novos tokens para mensagens de email

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/lilacs-journal-selection#48]
Criar token para exibir nome do editor no corpo das mensagens de email.

**Comment by AngelicaSAPaula** [comment]
Além do editor, é possível colocar o nome do destinatário de cada e-mail?

Na mensagem de confirmação de ativação do cadastro, é possível incluir o perfil no qual o usuário foi designado?

**Comment by wilsonmoura** [comment]
> Na mensagem de confirmação de ativação do cadastro, é possível incluir o perfil no qual o usuário foi designado?

Não será possível esse ajuste, pois as ações de ativação da conta de usuário e designação de perfis são realizadas em momentos e locais diferentes.

**Comment by suelisuga** [comment]
Ao receber mensagem para configuração de senha tive problemas com o nome do usuário e com o link propriamente dito, que nao abriu.

Segue resultado de meu cadastramento como parecerista:
**%username%,**

Devido ao conhecimento na sua área de atuação, tomamos a liberdade de cadastrá-lo na lista de avaliadores de mérito científico de periódicos em análise para indexação na LILACS.

Seu cadastro não significa assumir responsabilidade alguma, apenas permitindo-nos solicitar a avaliação de submissões. 

Caso deseje ser removido da lista, basta entrar em contato a qualquer tempo solicitando sua remoção.

Para definir sua senha, acesse: **https://avaliacao.lilacs.homolog.bvsalud.org/public/account/reset_my_password?hashcode=544501b03db48c28dee7e5b89c5a69c5.**

Esperamos poder contar com sua colaboração para garantir a qualidade da LILACS!

Atenciosamente,

SELEÇÃO DE PERIÓDICOS LILACS BRASIL
BIREME | Departamento de Evidência e Inteligência para Ação em Saúde 
OPAS/OMS
http://red.bvsalud.org/lilacs/es/editor/

Mensagem de erro quando tentei abrir o link para configuração da senha:
![image](https://user-images.githubusercontent.com/13105683/62127892-90332980-b2a9-11e9-871d-c03c6ca6f372.png)

Obrigada!
Sueli
