### ISSUE TITLE
Visualização Ad Hoc

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#52]
Atualmente, o usuário com perfil ad-hoc está conseguindo visualizar todos os periódicos submetidos e os comentários.

Ele só pode ver o peiródico em que foi designado para avaliação e, após realizada a avaliação (ou caso a secretaria o exclua do processo), ele não poderá mais ter acesso ao periódico.

Ele também não pode ver os comentários do processo

**Comment by wilsonmoura** [comment]
As questões relacionadas ao recurso de comentários serão analisadas em #2 e #14.
