### ISSUE TITLE
Desativação do item "Painel de Controle" no Menu

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#55]
Favor desabilitar esta função, uma vez que as informações que aparecem nela estão disponíveis em outros locais.

**Comment by AngelicaSAPaula** [comment]
É possível deixar essa função somente para os membros do **Comitê** e **Ad Hoc** com o label "_Periódicos Avaliados_"? 

Mas, nesta visualização, eles só podem ver os metadados e a própria avaliação (respostas) e não o processo completo

**Comment by AngelicaSAPaula** [comment]
Chamado aberto #82

**Comment by wilsonmoura** [comment]
Realizado em #82
