### ISSUE TITLE
Incluir campo em perfil de usuário

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#59]
Favor incluir um campo "Áreas de interesse / atuação" no formulário de criação de usuário.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula qual lista controlada devemos aplicar nesse novo campo? Especialidades ou Áreas Temáticas?

**Comment by AngelicaSAPaula** [comment]
Especialidades

**Comment by AngelicaSAPaula** [comment]
Favor abrir um campo aberto onde possamos colocar outras especialidades que não as da lista controlada!
