### ISSUE TITLE
Ajustar créditos da página para a BIREME/OPAS/OMS

### ISSUE THREAD

**Issue by suelisuga** [bireme/lilacs-journal-selection#78]
Ajustar créditos da página para a BIREME/OPAS/OMS.

![image](https://user-images.githubusercontent.com/13105683/62081456-10fe1100-b229-11e9-8906-0a7209e3d97d.png)

@renatomurasaki seria errado utilizar os creditos. termos de uso e política de privacidade assim como está no sistema FI-Admin?
- Termos de uso: http://politicas.bireme.org/terminos/es/
- Política de privacidad: http://politicas.bireme.org/privacidad/es/

![image](https://user-images.githubusercontent.com/13105683/62081845-dc3e8980-b229-11e9-988b-3fd24f4afb0e.png)

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
Esse texto já foi localizado e ajustado na página de gestão das traduções.
