### ISSUE TITLE
Ajustar apresentação do banner com o logo da LILACS para telas grandes e de celular

### ISSUE THREAD

**Issue by suelisuga** [bireme/lilacs-journal-selection#79]
Prezados,

O logo da LILACS está muito colado com o nome "Plataforma de Avaliação de Periódicos LILACS"

![image](https://user-images.githubusercontent.com/13105683/62082036-4d7e3c80-b22a-11e9-807c-8c748aa51160.png)

Se a tela é widescreen o logo da LILACS desaparece (tela do Wilson).

Se acessamos via celular, fica mais desconfigurado:
![image](https://user-images.githubusercontent.com/13105683/62082363-080e3f00-b22b-11e9-8789-7bf96f8ff21c.png)

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
Os ajustes forma realizados pela @pierrima. Com relação ao acesso via celular, o sistema não possui versão responsiva, pois foi desenvolvida especificamente para acesso desktop.
