### ISSUE TITLE
Ajustar letras do perfil à função/permissão que tem no sistema

### ISSUE THREAD

**Issue by suelisuga** [bireme/lilacs-journal-selection#80]
Pf. ajustar as letras que informam o papel desempenhado pelo usuário no sistema:
![image](https://user-images.githubusercontent.com/13105683/62128872-bd80d700-b2ab-11e9-8341-1ebebd06a2a6.png)

Ao invés de
I - Investigador ===>E - Editor de Periódico
S - Secretaria ====> OK
M - Membro Comitê => C - Membro do Comitê de Avaliação
M - Membro Comitê  => P - Parecerista Ad Hoc
A - Administrador ==> OK

Obrigada!
Sueli

**Comment by wilsonmoura** [comment]
O sistema usa a primeira letra dos nomes de cada perfil para exibir essas letras. Sendo assim, a única que foi possível alterar foi a letra para identificar o perfil Editor.
