### ISSUE TITLE
Desativar ícone "Enviar avaliação do periódico"

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#83]
Na área de "Periódicos avaliados", retirar ícone de "Enviar avaliação do periódico".

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula por favor, poderia incluir um print dessa tela para que possamos avaliar melhor esse detalhe?

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura o problema é que o ícone para avaliações ativas e as que já foram realizadas estão iguais, o que pode causar confusão.

![image](https://user-images.githubusercontent.com/47643830/62725312-4229ce80-b9eb-11e9-9ba6-55e6adbdc4cd.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula de acordo com a issue #101, incluímos uma label flutuante para que o usuário saiba qual é a funcionalidade desse ícone (veja imagem). Dessa forma, o usuário poderá identificar qual é a função que será acionada ao clicar no ícone.

![screenshot-avaliacao lilacs homolog bvsalud org-2019 08 08-15-00-41](https://user-images.githubusercontent.com/3779520/62726314-5cfd4280-b9ed-11e9-857f-48b6139e95f1.png)
