### ISSUE TITLE
Colocar data de seleção de pareceristas

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#84]
Favor criar uma coluna com a data em que os membros ad hoc e do comitê foram selecionados para realizar uma avaliação, para que consigamos ter um controle maior de quando devemos enviar o lembrete.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula esse dado já existe na tabela que exibe a relação de pareceristas escolhidos (veja imagem).

![screenshot-avaliacao lilacs homolog bvsalud org-2019 08 08-14-45-53](https://user-images.githubusercontent.com/3779520/62725382-6a193200-b9eb-11e9-955f-5add242f9629.png)
