### ISSUE TITLE
Comentários continuam sendo vistos por todos

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#86]
Os comentários voltaram a ser visualizados por todos os perfis.

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula essa demanda ainda não foi resolvida e será tratada em outras issues que já foram criadas (#14 e #73). Peço que evite a duplicação de issues para não confundir as demandas já existentes sobre o mesmo tema.

**Comment by wilsonmoura** [comment]
Resolvido em #73
