### ISSUE TITLE
Parecerista / Comitê - permitir enviar avaliação sem salvar como rascunho

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/lilacs-journal-selection#87]
Habilitar a opção "Salvar e enviar" para que seja possível enviar a avaliação sem ter que salvar como rascunho antes

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula o botão **salvar e enviar** está na última aba (Revisão). A única coisa que fiz foi atualizar a label desse botão nas outras abas.

**Comment by AngelicaSAPaula** [comment]
@wilsonmoura pareceristas ad hoc e membros do comitê só visualizam uma aba, a de avaliação.

![image](https://user-images.githubusercontent.com/47643830/62296985-a3c7c700-b446-11e9-9e90-1f3d7b14e17e.png)

**Comment by wilsonmoura** [comment]
@AngelicaSAPaula não entendi essa questão. Na página do formulário de avaliação não existe aba, pois a página serve somente para enviar o parecer. Existe outra necessidade nessa página? Se sim, abrir outra issue sobre esse tema.
